# Generated by Django 3.2 on 2022-01-24 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('cost', models.IntegerField(help_text='cost', null=True)),
                ('description', models.CharField(max_length=252, null=True)),
                ('code', models.CharField(max_length=20, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrintOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startPage', models.IntegerField(null=True)),
                ('endpage', models.IntegerField(null=True)),
                ('frontAndBack', models.BooleanField(null=True)),
                ('coloured', models.BooleanField(default=False, null=True)),
            ],
            options={
                'ordering': ['endpage'],
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email', max_length=254, null=True)),
                ('phoneNumber', models.CharField(help_text='phone number', max_length=15, null=True)),
                ('name', models.CharField(help_text='Name', max_length=30, null=True)),
                ('address', models.CharField(help_text='Address', max_length=30, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='select the file to upload', null=True, upload_to='')),
                ('fileurl', models.CharField(blank=True, help_text='url of file', max_length=30, null=True)),
                ('pages', models.IntegerField(help_text='how many copies', null=True)),
                ('notes', models.CharField(help_text='notes', max_length=200, null=True)),
                ('price', models.IntegerField(help_text='price of order', null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'pending'), (1, 'processing'), (2, 'ready'), (3, 'delivered')], default=0, help_text='Order status', null=True)),
                ('printOptions', models.ForeignKey(help_text='print options', null=True, on_delete=django.db.models.deletion.CASCADE, to='joskiprint.printoptions')),
                ('userDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='joskiprint.userdetails')),
            ],
            options={
                'ordering': ['-price'],
            },
        ),
    ]
