# Generated by Django 3.2 on 2022-02-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joskiprint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='price of order', max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='cost', max_digits=5, null=True),
        ),
    ]
