# Generated by Django 3.2 on 2022-03-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joskiprint', '0005_alter_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='order date'),
        ),
    ]
